config/routes.rb
Rails.application.routes.draw do
  root    'microposts#index'
  get     '/',            to: 'microposts#index'
  get     'policy',       to: 'home#policy'
  get     'terms',        to: 'home#terms'
  get     'signup',       to: 'users#new'
  get     '/login',       to: 'sessions#new'
  post    '/login',       to: 'sessions#create'
  delete  '/logout',      to: 'sessions#destroy'
  post    'set_occupations', to: 'occupations#set_occupations'
  post    '/users/guest_sign_in', to: 'users#guest_sign_in'
  get     'likes/create'
  get     'likes/destroy'

  resources :users do
    resources :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'bookmarklist' => 'bookmarks#bookmarklist', as: 'bookmarklist'
  end
 
  resources :microposts, only: %i[index new create destroy search show] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    collection do
      get :search
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :micropost, counter_cache: :likes_count
  validates :micropost, uniqueness: { scope: :user_id }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_micropost

  def create
    @like = Like.create(user_id: current_user.id, micropost_id: params[:micropost_id])
    @likes = Like.where(micropost_id: params[:micropost_id])
    @micropost.reload
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, micropost_id: params[:micropost_id])
    like.destroy
    @likes = Like.where(micropost_id: params[:micropost_id])
    @micropost.reload
  end

  private

    def set_micropost
      @micropost = Micropost.find(params[:micropost_id])
    end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if logged_in? %>

  <% unless micropost.like_user(current_user.id).blank? %>
    <%= link_to micropost_like_path(micropost_id: micropost.id ,id: micropost.likes[0].id), method: :delete, remote: true do %>
      <div class="vertical_like">
        <div>
          <i class="material-icons palevioletred">favorite</i>
        </div>
        <div>
          <%= micropost.likes_count %>
        </div>
      </div>
    <% end %>
  <% else %>
    <%= link_to micropost_likes_path(micropost.id), method: :post, remote: true do %>
        <div class="no_like">
          <div>
            <i class="material-icons">favorite_border</i>
          </div>
          <div>
            <%= micropost.likes_count %>
          </div>
        </div>
    <% end %>
  <% end %>

<% else %>
  <div class="no_like">
    <i class="material-icons">favorite_border</i>
    <span>
      <%= micropost.likes_count %>
    </span>
  </div>
<% end %>

app/views/likes/create.js.erb
$("#likes_buttons_<%= @micropost.id %>").html("<%= j(render partial: 'likes/like', locals: {micropost: @micropost}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @micropost.id %>').html("<%= j(render partial: 'likes/like', locals: {micropost: @micropost}) %>");