config/routes.rb
Rails.application.routes.draw do
  root    'microposts#index'
  get     '/',            to: 'microposts#index'
  get     'policy',       to: 'home#policy'
  get     'terms',        to: 'home#terms'
  get     'signup',       to: 'users#new'
  get     '/login',       to: 'sessions#new'
  post    '/login',       to: 'sessions#create'
  delete  '/logout',      to: 'sessions#destroy'
  post    'set_occupations', to: 'occupations#set_occupations'
  post    '/users/guest_sign_in', to: 'users#guest_sign_in'
  get     'likes/create'
  get     'likes/destroy'

  resources :users do
    resources :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'bookmarklist' => 'bookmarks#bookmarklist', as: 'bookmarklist'
  end
 
  resources :microposts, only: %i[index new create destroy search show] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    collection do
      get :search
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_one_attached :image
  attr_accessor :remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 200 },
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :birthday, presence: true
  #画像アップロードのための記述
  mount_uploader :avatar, AvatarUploader

  class << self #Userクラスを呼び出す
    #渡された文字列のハッシュを返す
    def digest(string) #User.が不要
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    #ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end
  end
    
  #永続セッションのためにユーザをデータベースに記憶
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end

  #フォロー機能のメソッドを記述
  def follow(user_id)
    relationships.create(follow_id: user_id) unless (self == user_id)
  end

  def unfollow(user_id)
    relationships.find_by(follow_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def guest?(user)
    user
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user,   only: [:edit, :update]
  before_action :logged_in_user,   only: [:index, :edit, :update, :destroy]
  before_action :admin_user,   only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])
    @micropost_counts = @users.joins(:microposts).count
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page]).preload(:job_discriptions, :occupation, :likes)
    @bookmarks = Bookmark.where(user_id: current_user.id)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "新規登録が完了しました！"
      redirect_to root_url
    else
      render action: "new"
    end
  end

  def edit
    return unless guest_user?(current_user)
    flash[:danger] = "ゲストユーザーは編集できません"
    redirect_to root_url
  end

  def update
    if @user.update(user_params)
      flash[:success] = "プロフィールを更新しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    if guest_user?(current_user)
      flash[:danger] = "ゲストユーザーは削除できません"
      redirect_to root_url
    else
      User.find(params[:id]).destroy
      flash[:success] = "削除が完了しました"
      redirect_to root_path
    end
  end

  def guest_sign_in
    user = User.find_or_create_by!(email: 'guest@example.com') do |guest_user|
      guest_user.password = SecureRandom.urlsafe_base64
      guest_user.name = "ゲストユーザー"
      guest_user.birthday = "1994-01-01"
    end
    session[:user_id] = user.id
    flash[:success] = "ゲストユーザーとしてログインしました"
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :birthday, :biography, :avatar, :remove_avatar,  :password_confirmation)
    end

  #正しいユーザか確認
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  #管理者かどうか確認
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  #ログイン済みユーザーかどうか確認
  def logged_in_user
    return if logged_in?
    flash[:danger] = "ログインしてください"
    redirect_to login_url
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_user.html.erb
  <li>
    <%= link_to user.name, user %>
    <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
                              data: { confirm: "本当に削除しますか？"} %>
    <% end %>
  </li>

app/views/users/edit.html.erb
<% provide(:title, "マイページを編集") %>
<div class="row">
  <div class="col-xs-12">
    <h3>マイページを編集<span class="material-icons md-36">settings</span></h3>
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <div class="field-item">
          <%= f.label :name, '名前' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="field-item">
          <%= f.label :avatar, 'プロフィール画像' %>
          <%= f.file_field :avatar %>
        </div>

        <div class="check-box-area">
          <%= f.check_box :remove_avatar %>
          <p>現在設定している画像をリセットする</p>
        </div>
  
        <div class="field-item">
          <%= f.label :email, 'メールアドレス' %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
  
        <div class="field-item">
          <%= f.label :birthday, '生年月日' %>
          <%= f.date_field :birthday, class: 'form-control' %>
        </div>
  
        <div class="field-item">
          <%= f.label :biography, '自己紹介' %>
          <%= f.text_area :biography, class: 'form-control' %>
        </div>

        <div class="field-item">
          <%= f.label :password, 'パスワード' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div class="form-item">

        <div class="field-item">
          <%= f.label :password_confirmation, "パスワード確認用" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <div class="field-item">
          <%= f.submit "変更を保存", class: "btn btn-primary" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "ユーザー一覧") %>
<h2>ユーザー一覧<span class="material-icons md-36">groups</span></h2>

<ul class="user-index-container">
  <% @users.each do |user| %>
    <hr>
    <a href="/users/<%= user.id %>">
      <div class="user-index row">
        <div class="img-area col-xs-4">
          <div>
            <% if user.avatar? %>
              <%= image_tag user.avatar.url %>
            <% else %>
              <%= image_tag ("default.jpg") %>
            <% end %>
          </div>
        </div>

        <ul class="user-index-item col-xs-7">
          <li>
            <p><%= user.name %></p>
          </li>
          <li><%= (Date.today.strftime("%Y%m%d").to_i - user.birthday.strftime("%Y%m%d").to_i) / 10000 %>歳</li>

          <li>投稿数（<%= @micropost_counts %>）</li>
        </ul>
      </div>
    </a>
    <% if current_user.admin? && !current_user?(user) %>
      <div>
        <p><%= link_to "削除（管理者権限）", user, method: :delete, data: { confirm: "本当に削除しますか？"} %></p>
      </div>
    <% end %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h2>新規登録</h2>
<div class="row">
  <div class="col-md-12">
    <%= form_with(model: @user, local:true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="field">
        <div class="field-item">
          <%= f.label :name, "名前" %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="field-item">
          <%= f.label :email, "メールアドレス" %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>

        <div class="field-item">
          <%= f.label :birthday, "生年月日（西暦）" %>
          <%= f.date_field :birthday, class: 'form-control' %>
        </div>

        <div class="field-item">
          <%= f.label :password, "パスワード" %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class="field-item">
          <%= f.label :password_confirmation, "パスワード(確認用)" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <div class="field-item">
          <%= f.submit "登録", class: "btn btn-primary" %>
        </div>
        
        <div class="field-item">
          <p>登録済みの場合 <%= link_to "ログインはこちら", login_path %> </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "プロフィール") %>
<section class="profile-container">
  <div class="profile-area row">
    <div class="img-area col-xs-5 col-md-3">
      <% if @user.avatar? %>
        <div class="img-item">
          <%= image_tag @user.avatar.url %>
        </div>
      <% else %>
        <%= image_tag ("default.jpg") %>
      <% end %>
    </div>
    
    <div class="basic-info col-xs-9 col-md-8">
      <div class="basic-info-item">
        <p><%= @user.name %></p>
      </div>
      <!-- 生年月日から年齢を逆算 -->
      <% if !guest_user?(@user) %>
        <p class="basic-info-item"><%= (Date.today.strftime("%Y%m%d").to_i - @user.birthday.strftime("%Y%m%d").to_i) / 10000 %>歳</p>
      <% end %>

      <% if current_user?(@user) && !guest_user?(@user) %>
        <div class="basic-info-item">
          <%= link_to "マイページを編集", edit_user_path(current_user), class: "basic-info-item" %>
        </div>
      <% end %>

      <p class="basic-info-item">投稿数 (<%= @user.microposts.count %>)</p>

      <%= render partial: 'relationships/follows_count' %>
      
      <% if current_user?(@user) %>
        <div class="basic-info-item">
          <%= link_to "ブックマーク一覧", user_bookmarklist_path(current_user), class: "basic-info-item" %>
        </div>
      <% end %>
      
      <% if !guest_user?(@user) %>
        <div class="basic-info-item">
          <p>自己紹介:</p>
          <p>
            <%= @user.biography %>
          </p>
        </div>
      <% end %>
      
      <%= render partial: 'relationships/follow_button' %>

      <% if current_user?(@user) && !guest_user?(@user) %>
        <div class="basic-info-item">
          <%= link_to "アカウントを削除", @user, method: :delete, data: { confirm: "本当に削除しますか？"}, class: "basic-info-item" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

<div>
  <% if @user.microposts.any? %>
    <ol class="profile-post-area">
      <%= render 'microposts/post_content' %>
    </ol>
    <%= will_paginate @microposts %>
  <% end %>
</div>