config/routes.rb
Rails.application.routes.draw do
  root    'microposts#index'
  get     '/',            to: 'microposts#index'
  get     'policy',       to: 'home#policy'
  get     'terms',        to: 'home#terms'
  get     'signup',       to: 'users#new'
  get     '/login',       to: 'sessions#new'
  post    '/login',       to: 'sessions#create'
  delete  '/logout',      to: 'sessions#destroy'
  post    'set_occupations', to: 'occupations#set_occupations'
  post    '/users/guest_sign_in', to: 'users#guest_sign_in'
  get     'likes/create'
  get     'likes/destroy'

  resources :users do
    resources :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'bookmarklist' => 'bookmarks#bookmarklist', as: 'bookmarklist'
  end
 
  resources :microposts, only: %i[index new create destroy search show] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    collection do
      get :search
    end
  end
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  belongs_to :occupation
  belongs_to :industry
  
  has_many :job_discriptions, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  accepts_nested_attributes_for :job_discriptions, allow_destroy: true
  default_scope -> { order(created_at: :desc) }
  validates :job_discriptions, presence: true

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def bookmarked_by?(user)
    bookmarks.exists?(user_id: user)
  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: %i[create destroy]
  before_action :correct_user, only: :destroy

  def index
    @users = User.where(activated: true)
    @microposts = Micropost.all.order(created_at: :desc).limit(15).preload(:user, :job_discriptions, :occupation, :likes)
    gon.industries = Industry.all.to_json only: %i[id name]
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "投稿が完了しました"
      redirect_to root_path
    else
      flash[:danger] = "投稿に失敗しました"
      redirect_to request.referrer || root_path
    end
  end

  def new
    @micropost = current_user.microposts.build if logged_in?
    gon.industries = Industry.all.to_json only: %i[id name]
  end

  def show
    @micropost = Micropost.find(params[:id])
    @job_discription = JobDiscription.find(params[:id])
    @comments = @micropost.comments
    @comment = current_user.comments.new
    @user = User.where(params[:id])
  end

  def destroy
    @micropost.destroy
    flash[:success] = "投稿を削除しました"
    redirect_to request.referrer || root_url
  end

  def search
    if params[:id].present?
      gon.industries = Industry.all.to_json only: %i[id name]
      @occupation = Occupation.find(params[:id])
      @microposts = Micropost.where("occupation_id LIKE ?", "%#{params[:id]}%").paginate(page: params[:page])
    else
      flash[:danger] = "業界と職種を選択してください"
      redirect_to request.referrer || root_path
    end
  end

  private
    def micropost_params
      params.require(:micropost).permit(:industry_id, :occupation_id, :job, :busyness, :seniority_year, :complement,
      job_discriptions_attributes: [
        :id,
        :content,
        :time,
        :_destroy
      ])
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_comment_form.html.erb
<h3 style="text-align: left;">コメント<span class="material-icons md-36">textsms</span></h3>
<% if @micropost.comments.any? %>
  <% @comments.each do |c| %>
    <div>
      <a href="/users/<%= c.user.id %>"><%= c.user.name %></a>
      <p><%= c.comment %></p>
      <% if current_user.id == c.user.id %>
        <%= link_to "削除", micropost_comment_path(@micropost, c), method: :delete %>
      <% end %>
      <hr>
    </div>
  <% end %>
<% end %>

<%= form_with( model:[@micropost, @comment], method: :post, class:"comment-form") do |f| %>
  <div>
    <%= f.text_area :comment, placeholder: "コメントを入力" %>
  </div>
  <%= f.hidden_field :micropost_id, value: @micropost.id %>
  <%= f.hidden_field :user_id, value: @comment.user_id %>
  <div class="btn">
    <%= f.submit 'コメントする' %>
  </div>
<% end %>

app/views/microposts/_job_discription_fields.html.erb
<div class="nested-fields">
  <div class="nested-fields-block">
    <%= f.label :time, "時間" %>
    <%= f.time_field :time %>
  </div>
  <div class="nested-fields-block">
    <%= f.label :content, "職務内容" %>
    <%= f.text_area :content, class: "content-width" %>
  </div>
  <%= link_to_remove_association "削除", f %>
</div>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="occupation"><%= micropost.occupation %></span>
  <span class="job"><%= micropost.job %></span>
  <span class="timestamp"><%= time_ago_in_words(micropost.created_at) %>前
    <% if current_user?(micropost.user) %>
    <%= link_to "投稿を削除", micropost, method: :delete, data: { confirm: "本当に削除しますか？"} %>
    <% end %>
  </span>
</li>

app/views/microposts/_post_content.html.erb
<% @microposts.each do |post| %>
  <div class="posts-index-item row">
    <div class="posts-box col-12">

      <div class="basic-info">
        <% if logged_in? %>
          <div class="basic-info-item">
            <% unless current_user?(post.user) %>
              <p><a href="/users/<%= post.user.id %>"><%= post.user.name %></a>さんの投稿<span class="material-icons md-18">account_circle</span></p>
            <% else %>
              <p>自分の投稿</p>
            <% end %>
          </div>

          <div class="basic-info-item">
            <p><%= post.created_at.strftime("%Y年%-m月%-d日%H時%M分") %></p>
          </div>
        <% else %>
        <p><%= post.user.name %>さんの投稿<span class="material-icons md-18">account_circle</span></p>
        <% end %>
  
        <div class="basic-info-item">
          <p>職種<span class="material-icons md-18">work_outline</span><span> | </span><%= post.occupation.name %></p>
        </div>

        <div class="basic-info-item">
          <p>職業<span class="material-icons md-18">engineering</span><span> | </span><%= post.job %></p>
        </div>

        <div class="basic-info-item">
          <p>時期<span class="material-icons md-18">date_range</span><span> | </span><%= post.busyness %></p>
        </div>
        
        <div class="basic-info-item schedule">
          <p>スケジュールと職務内容<span class="material-icons md-18">note_alt</span></p>
        </div>
      </div>
  
      <div>
        <% post.job_discriptions.each do |discription| %>
          <div class="discription-area col-12">
            <p><%= discription.time.strftime( "%H時%M分" ) %></p>
            <p><%= discription.content %></p>
          </div>
        <% end %>
      </div>

      <div class="basic-info">
        <p class="basic-info-item">補足情報<span class="material-icons md-18">error_outline</span></p>
        <% if post.complement.present? %>
          <p><%= post.complement %></p>
        <% else %>
          <p>なし</p>
        <% end %>
      </div>
      
      <div class="reaction-area">
        <div id="likes_buttons_<%= post.id %>" class="like-button">
          <%= render partial: 'likes/like', locals: { micropost: post, likes: @likes} %>
        </div>

        <div>
          <% if logged_in? %>
            <a href="/microposts/<%= post.id %>"><%= '詳細ページへ' %><span class="material-icons md-18">exit_to_app</span></a>
          <% else %>
            <%= '※ログインか新規登録で詳細ページへ' %>
          <% end %>
        </div>

        <div>
          <% if current_user?(@user) %>
            <%= link_to "投稿を削除", post, method: :delete, data: { confirm: "本当に削除しますか？"} %>
          <% end %>
        </div>

      </div>

    </div>
  </div>
<% end %>

app/views/microposts/_search_form.html.erb
<h2>職業を検索<span class="material-icons md-36">content_paste_search</span></h2>
<div class="row">
  <%= form_with url: search_microposts_path, method: :get, id: 'example_form', class: 'col-xs-11 col-sm-11 col-lg-8 example-form',  local: true do |f| %>
    <%= f.select :id, nil, {prompt: "①業界を選択"}, {'v-model': 'selectedIndust', '@change': 'getOccupations(selectedIndust)'} do %>
      <option v-for="industry in industries" :key="industry.name" :value="industry.id">
        {{industry.name}}
      </option>
    <% end %>

    <%= f.select :id, nil, {prompt: "②職種を選択"} do %>
      <option v-for="occupation in occupations" :key="occupation.name" :value="occupation.id">
        {{occupation.name}}
      </option>
    <% end %>

    <%= f.submit '③検索' %>
  <% end %>
</div>

app/views/microposts/_show_post_content.html.erb
<div class="posts-index-item row">
  <div class="posts-box col-12">

    <div class="basic-info">
      <div class="basic-info-item">
        <% unless current_user?(@micropost.user) %>
          <p><a href="/users/<%= @micropost.user.id %>"><%= @micropost.user.name %></a>さんの投稿<span class="material-icons md-18">account_circle</span></p>
        <% else %>
          <p>自分の投稿</p>
        <% end %>
      </div>

      <div class="basic-info-item">
        <p>職種<span class="material-icons md-18">work_outline</span><span> | </span><%= @micropost.occupation.name %></p>
      </div>

      <div class="basic-info-item">
        <p>職業<span class="material-icons md-18">engineering</span><span> | </span><%= @micropost.job %></p>
      </div>

      <div class="basic-info-item">
        <p>時期<span class="material-icons md-18">running_with_errors</span><span> | </span><%= @micropost.busyness %></p>
      </div>

      <div class="basic-info-item schedule">
        <p>スケジュールと職務内容<span class="material-icons md-18">date_range</span></p>
      </div>
    </div>

    <div>
      <% @micropost.job_discriptions.each do | discription | %>
        <div class="discription-area col-12">
          <p><%= discription.time.strftime( "%H時%M分" ) %></p>
          <p><%= discription.content %></p>
        </div>
      <% end %>
    </div>

    <div class="basic-info">
      <p class="basic-info-item">補足情報<span class="material-icons md-18">mode_edit</span></p>
      <% if @micropost.complement.present? %>
        <p><%= @micropost.complement %></p>
      <% else %>
        <p>なし</p>
      <% end %>
    </div>

    <div class="reaction-area">
      <div id="likes_buttons_<%= @micropost.id %>" class="like-button">
        <%= render partial: 'likes/like', locals: { micropost: @micropost, likes: @likes} %>
      </div>
      <%= render partial: 'bookmarks/bookmark' %>
      <div>
        <% if current_user?(@micropost.user) %>
          <%= link_to "投稿を削除", @micropost, method: :delete, data: { confirm: "本当に削除しますか？"} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/microposts/index.html.erb
<%= render 'microposts/search_form' %>

<h2 style="text-align: center;">新着投稿<span class="material-icons md-36">list_alt</span></h2>

<%= render 'microposts/post_content' %>

app/views/microposts/new.html.erb
<% provide(:title, "投稿") %>
<div class="row">
  <div class="col-xs-12">
    <% if logged_in? %>
      <h2>投稿<span class="material-icons md-36">create</span></h2>
      <%= form_with(model: @micropost, local: true, id: 'example_form', class: 'post-form') do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="field" >
          <div class="field-item">
            <%= f.label :industry, "業界（必須）" %>
            <%= f.select :industry_id, nil, {prompt: "①業界を選択"}, {'v-model': 'selectedIndust', '@change': 'getOccupations(selectedIndust)'} do %>
              <option v-for="industry in industries" :key="industry.name" :value="industry.id">
                {{industry.name}}
              </option>
            <% end %>
          </div>

          <div class="field-item">
            <%= f.label :occupation, "職種（必須）" %>
            <%= f.select :occupation_id, nil, {prompt: "②職種を選択"} do %>
              <option v-for="occupation in occupations" :key="occupation.name" :value="occupation.id">{{occupation.name}}</option>
            <% end %>
          </div>
          
          <div class="field-item">
            <%= f.label :job, "職業（任意）" %>
            <%= f.text_field :job, class: 'form-control' %>
          </div>
          
          <div class="field-item">
            <%= f.label :busyness, "忙しさ" %>
            <%= f.select :busyness, [["繁忙期", "繁忙期"], ["通常期", "通常期"], ["閑散期", "閑散期"]] %>
          </div>
          
          <div class="field-item">
            <%= f.label :seniority_year,  "勤続年数" %>
            <%= f.select :seniority_year, [["１年未満", "１年未満"], ["１年以上〜３年未満"], ["３年以上〜５年未満"], ["１０年以上"]] %>
          </div>
          
          <div class="field-item">
            <%= link_to_add_association 'クリックで職務内容を追加', f, :job_discriptions, data: { association_insertion_method: 'append' } %>
            <%= f.fields_for :job_discriptions do |discription| %>
              <%= render "job_discription_fields", f: discription %>
            <% end %>
          </div>
          
          <div class="field-item">
            <%= f.label :complement, "補足" %>
            <%= f.text_field :complement, class: 'form-control' %>
          </div>
          
          <div class="field-item">
            <%= f.submit "投稿", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>ログインしてください</p>
    <% end %>

  </div>
</div>

app/views/microposts/search.html.erb
<% provide(:title, "検索結果") %>
<%= render 'microposts/search_form' %>
<h3 style="text-align: center;"><%= @occupation.name %><br>の検索結果</h2>
<p style="text-align: center;"><span style="font-weight: bold;"><%= @microposts.count %></span>件見つかりました</p>
<tbody>
  <%= render 'microposts/post_content' %>
</tbody>
  <%= will_paginate %>

app/views/microposts/show.html.erb
<%= render 'microposts/show_post_content' %>
<%= render 'microposts/comment_form' %>