config/routes.rb
Rails.application.routes.draw do
  root    'microposts#index'
  get     '/',            to: 'microposts#index'
  get     'policy',       to: 'home#policy'
  get     'terms',        to: 'home#terms'
  get     'signup',       to: 'users#new'
  get     '/login',       to: 'sessions#new'
  post    '/login',       to: 'sessions#create'
  delete  '/logout',      to: 'sessions#destroy'
  post    'set_occupations', to: 'occupations#set_occupations'
  post    '/users/guest_sign_in', to: 'users#guest_sign_in'
  get     'likes/create'
  get     'likes/destroy'

  resources :users do
    resources :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'bookmarklist' => 'bookmarks#bookmarklist', as: 'bookmarklist'
  end
 
  resources :microposts, only: %i[index new create destroy search show] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  validates :user_id, uniqueness: { scope: :micropost_id }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  validates :comment, length: { minimum: 1 }, allow_nil: true
end

app/models/industry.rb
class Industry < ApplicationRecord
  has_many :occupations, dependent: :destroy
  has_many :microposts, dependent: :destroy
end

app/models/job_discription.rb
class JobDiscription < ApplicationRecord
  belongs_to :micropost
  validates :time, presence: true
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :micropost, counter_cache: :likes_count
  validates :micropost, uniqueness: { scope: :user_id }
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  belongs_to :occupation
  belongs_to :industry
  
  has_many :job_discriptions, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  accepts_nested_attributes_for :job_discriptions, allow_destroy: true
  default_scope -> { order(created_at: :desc) }
  validates :job_discriptions, presence: true

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def bookmarked_by?(user)
    bookmarks.exists?(user_id: user)
  end

end

app/models/occupation.rb
class Occupation < ApplicationRecord
  belongs_to :industry
  has_many :microposts, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_one_attached :image
  attr_accessor :remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 200 },
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :birthday, presence: true
  #画像アップロードのための記述
  mount_uploader :avatar, AvatarUploader

  class << self #Userクラスを呼び出す
    #渡された文字列のハッシュを返す
    def digest(string) #User.が不要
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    #ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end
  end
    
  #永続セッションのためにユーザをデータベースに記憶
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end

  #フォロー機能のメソッドを記述
  def follow(user_id)
    relationships.create(follow_id: user_id) unless (self == user_id)
  end

  def unfollow(user_id)
    relationships.find_by(follow_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def guest?(user)
    user
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "だいJobそ？"
    page_title.empty? ? base_title : page_title + "|" + base_title
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/occupations_helper.rb
module OccupationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #ログイン
  def log_in(user)
    session[:user_id] = user.id
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  #ログアウト
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  #ユーザのセッションを永続的にする
  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  #現在ログイン中のユーザーを返す
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.encrypted[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def guest_user
    user_id = User.find_by(id: "15")
    @guest_user = user_id
  end

  def guest_user?(user)
    user && user == guest_user
  end
  #渡されたユーザがカレントユーザーであればtrueを返す
  def current_user?(user)
    user && user == current_user
  end

  #ログイン中 -> true, その他 -> false
  def logged_in?
    !current_user.nil?
  end

  #記憶したURL（もしくはデフォルト値）にリダイレクト
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  #アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.erb
<footer class="p-3 mb-2 text-center bg- col-12 col-md-12">
  <div>

    <%= link_to 'プライバシーポリシー', page_path('policy') %>
    <%= link_to '利用規約', page_path('terms') %>

    <p>© daijobso All Rights Reserved.</p>
  </div>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  
  <%= include_gon %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-238147462-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-238147462-2');
</script>
  </head>

app/views/layouts/_header.html.erb
<header row>
  <!-- ハンバーガーメニュー -->
  <div id="hamburger-app">
      <h1><a href="/">だいjobそ？</a></h1>
      <button type="button" class="menu-btn js-btn" v-on:click="open=!open" >
        <span class="btn-line"></span>
      </button>

      <div class="menu" v-bind:class="{'is-active' : open }">
        <% if logged_in? %>
            <div class="menu__item">
              <%= link_to root_path, data: {"turbolinks" => false} do %>
                <div>
                  <span class="material-icons md-36">home</span>
                </div>
                <div class="mask mask01">
                  <p>ホーム</p>
                </div>
              <% end %>
            </div>


          <div class="menu__item">
            <%= link_to users_path, data: {"turbolinks" => false} do %>
              <div>
                <span class="material-icons md-36">groups</span>
              </div> 
              <div class="mask mask01">
                <p>ユーザー</p>
              </div>
            <% end %>
          </div>

          <div class="menu__item">
            <%= link_to new_micropost_path, data: {"turbolinks" => false} do %>
              <div>
                <span class="material-icons md-36">create</span>
              </div>
              <div class="mask mask01">
                <p>投稿</p>
              </div>
            <% end %>
          </div>

          <div class="menu__item">
            <%= link_to current_user, data: {"turbolinks" => false} do %>
              <div>
                <span class="material-icons md-36">person</span>
              </div>
              <div class="mask mask01">
                <p>マイページ</p>
              </div>
            <% end %>
          </div>

          <div class="menu__item">
            <%= link_to logout_path, method: :delete do %>
              <div>
                <span class="material-icons md-36">logout</span>
              </div>
              <div class="mask mask01">
                <p>ログアウト</p>
              </div>
            <% end %>
          </div>
        <% else %>

          <div class="menu__item">
            <%= link_to login_path do %>
              <div>
                <span class="material-icons md-36">login</span>
              </div>
              <div class="mask mask01">
                <p>ログイン</p>
              </div>
            <% end %>
          </div>

          <div class="menu__item">
            <%= link_to signup_path do %>
              <div>
                <span class="material-icons md-36">person_add</span>
              </div>
              <div class="mask mask01">
                <p>新規登録</p>
              </div>
            <% end %>
          </div>
          
          <div class="menu__item">
            <%= link_to users_guest_sign_in_path, method: :user do %>
            <div>
              <span class="material-icons md-36">hail</span>
            </div>
            <div class="mask mask01">
              <p>ゲストログイン</p>
            </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    
    
    <%= javascript_pack_tag 'hello_vue' %>
    <%= stylesheet_pack_tag 'hello_vue' %>
  </body>
</html>

app/views/pages/policy.html.erb
プライバシーポリシーです

app/views/pages/terms.html.erb
利用規約が入ります。

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      フォームに <%= pluralize(object.errors.count, "個のエラーがあります") %>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>